package com.compiler.websocket.model;

import jakarta.validation.constraints.NotBlank;
import lombok.*;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class SqsPayload {

    @NotBlank
    private String job_id;      // generated by server

    @NotBlank
    private String language;      // java, cpp, python

    @NotBlank
    private String file_name;

    @NotBlank
    private String source_code;

}